# Generated by Django 4.2.27 on 2025-12-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PokerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stakes', models.CharField(choices=[('00', 'All'), ('12', '1/2'), ('13', '1/3'), ('25', '2/5'), ('55', '5/5'), ('510', '5/10'), ('2040', '20/40')], max_length=20)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('buy_in', models.IntegerField()),
                ('cash_out', models.IntegerField()),
                ('notes', models.TextField(blank=True, max_length=5000, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('casino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.casino')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
