# Generated by Django 4.2.27 on 2025-12-12 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=100)),
                ('number_last4', models.CharField(blank=True, help_text='Last 4 digits, optional, for reference only.', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('is_auto_pay', models.BooleanField(default=False, help_text='Checked if this bill is paid automatically.')),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload an image/PDF of the paid bill or receipt.', null=True, upload_to='bills/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='john.account')),
            ],
            options={
                'ordering': ['is_paid', 'due_date', 'name'],
            },
        ),
    ]
