# Generated by Django 4.2.27 on 2025-12-15 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount of money withdrawn.', max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the money actually left the account.')),
                ('method', models.CharField(choices=[('ACH', 'ACH / Bank transfer'), ('CARD', 'Debit / Credit card'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='ACH', help_text='How the withdrawal was made.', max_length=10)),
                ('memo', models.CharField(blank=True, help_text="Short description (e.g. 'Electric bill', 'ATM withdrawal').", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Which account the money came out of.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='john.account')),
                ('bill', models.ForeignKey(blank=True, help_text='Optional: link to the bill this withdrawal paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='john.bill')),
            ],
            options={
                'verbose_name': 'Account withdrawal',
                'verbose_name_plural': 'Account withdrawals',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
