# Generated by Django 4.2.27 on 2025-12-15 18:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0002_accountwithdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['active', 'due_day', 'name']},
        ),
        migrations.RemoveField(
            model_name='bill',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='bill',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck if this bill is no longer active.'),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='Day of the month this bill is due (1–31).'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='is_auto_pay',
            field=models.BooleanField(default=False, help_text='Checked if this bill is paid automatically each month.'),
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_image', models.ImageField(blank=True, help_text='Upload an image/PDF of the paid bill or receipt.', null=True, upload_to='bills/receipts/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='john.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='john.bill')),
            ],
            options={
                'verbose_name': 'Bill payment',
                'verbose_name_plural': 'Bill payments',
                'ordering': ['-date_paid', '-id'],
            },
        ),
    ]
