# Generated by Django 4.2.27 on 2025-12-18 23:17

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0003_alter_bill_options_remove_bill_date_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('miles', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rate_per_mile', models.DecimalField(decimal_places=3, default=Decimal('0.655'), help_text='Reimbursement rate per mile.', max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Computed reimbursement amount (miles × rate).', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mileage entry',
                'verbose_name_plural': 'Mileage entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Reimbursement rate per hour.', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, help_text='Computed reimbursement amount (hours × rate).', max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work entry',
                'verbose_name_plural': 'Work entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
