# Generated by Django 4.2.27 on 2025-12-20 19:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0004_mileageentry_workentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileageentry',
            name='ending_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ending odometer reading.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mileageentry',
            name='starting_mileage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting odometer reading.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of work.', null=True),
        ),
        migrations.AddField(
            model_name='workentry',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time of work.', null=True),
        ),
        migrations.AlterField(
            model_name='mileageentry',
            name='miles',
            field=models.DecimalField(decimal_places=2, help_text='Total miles driven (calculated or manual).', max_digits=7),
        ),
        migrations.AlterField(
            model_name='mileageentry',
            name='rate_per_mile',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.210'), help_text='Reimbursement rate per mile.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, help_text='Total hours worked (calculated or manual).', max_digits=6),
        ),
    ]
