# Generated by Django 4.2.27 on 2025-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0005_mileageentry_ending_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileageentry',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total miles driven (calculated or manual).', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total hours worked (calculated or manual).', max_digits=6, null=True),
        ),
    ]
