# Generated by Django 4.2.27 on 2025-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('john', '0006_alter_mileageentry_miles_alter_workentry_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileageentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Computed reimbursement amount (miles × rate).', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='workentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Computed reimbursement amount (hours × rate).', max_digits=8, null=True),
        ),
    ]
